# Øving 2

Vi henviser til introduksjonsforelesningen for mer informasjon.


## Nettverk og matriser

En graf (nei ikke en graf som i matte 1) består av en mengde noder og en mengde pil. Hver pil ligger mellom to noder. Vi kommer til å gjøre det litt enklere ved at det er maks en pil mellom hvert par av noder. Vi tillater ikke løkker.

På hver pil kan vi legge et tall som vi kaller vekten til pilen. Hvis et nettverk ikke har vekter, så vil hver pil ha vekt $1$. Piler med vekt $0$ er ikke med i nettverket.

Vi bruker numpy for matematiske beregninger.


In [1]:
import numpy as np

Du kommer til å lære mye om nettverk igjennom bachelorgraden din. Både i matematikk 2 og i andre fag. Vi kommer ikke til å gå noe i dybden her. 

Det eneste vi trenger akkurat nå er "hva er et nettverk" og at "nettverk = matriser". Vi henviser til introduksjonsforelesningen for mer informasjon.

Vi kommer til å bruke tallene $0,1,\cdots,n$ som navn på nodene i nettverket.

Vi kan beskrive et nettverk som en liste tupler, hvor en tuppel $(i,j,w)$ betyr at det er en pil fra node $i$ til node $j$ med vekt $w$.

I en matrise så har vi tall $A[i,j]$. Vi kan tolke $A[i,j] = w$ som at det er en pil i nettverket fra $i$ til $j$ med vekt $0$. Det betyr egentlig at vi foretrekker å jobbe med radvektorer i denne øvingen.

Vi kunne også ha tolket $A[i,j]=w$ som at det er en pil $j$ til $i$ med vekt $w$. Det betyr at vi foretrekker å jobbe med kolonnevektorer.

Vi tillater ikke løkker i nettverket vårt. Det betyr at tallene på diagonalen ikke blir brukt. I alle eksemplene vi skal se på så skal summen i hver rad være lik $0$. Det betyr at vi må sette et negativt tall (lik minus av summen av de andre tallene i raden) i på diagonalplassen i hver rad.

I programmet under så har vi et nettverk og en matrise. De inneholder akkurat samme informasjon. Pass på at du forstår hvordan dette henger sammen før du går videre.

In [2]:
N = [(0, 1, 2.0), (1, 0, 3.0), (0, 2, 4.0), (2,0,5.0)]
print("Vi har nettverket",N,"som har",len(N),"piler")

M = np.array([[-6.0, 2.0, 4.0],[3.0, -3.0, 0.0], [5.0, 0.0, -5.0]])
print("Vi har matrisen M\n",M)
print("Matrisen M og nettverket N beskriver akkurat samme informasjon")

Vi har nettverket [(0, 1, 2.0), (1, 0, 3.0), (0, 2, 4.0), (2, 0, 5.0)] som har 4 piler
Vi har matrisen M
 [[-6.  2.  4.]
 [ 3. -3.  0.]
 [ 5.  0. -5.]]
Matrisen M og nettverket N beskriver akkurat samme informasjon


## Oppgave 1

a) Programmer funksjoner som tar et nettverk med et gitt antall noder som input og som returnerer den tilhørende matrisen.

b) Programmer en funksjon som tar en matrise som input og returnerer det tilhørende nettverket

Test funksjonene og forsikre deg om at alt er riktig før du går videre.

In [32]:
def tilMatrise(numberOfNodes, network):
    n = numberOfNodes
    matrix = np.zeros((n, n))
    
    for row, col, value in network:
        matrix[row][col] = value
    
    for i in range(n):
        matrix[i][i] = -np.sum(matrix[i])
    
    return matrix

def tilNettverk(matrix):
    network = []
    m, n = np.shape(matrix)
    
    for row in range(m):
        for col in range(n):
            if row != col and matrix[row][col] != 0:
                network.append((row, col, matrix[row][col]))
                
    return network

N = [(0, 1, 2.0), (1, 0, 3.0), (0, 2, 4.0), (2,0,5.0)]
M = np.array([
    [-6.0, 2.0, 4.0],
    [3.0, -3.0, 0.0],
    [5.0, 0.0, -5.0]
])

print(tilMatrise(3,N))
print(tilNettverk(M))

[[-6.  2.  4.]
 [ 3. -3.  0.]
 [ 5.  0. -5.]]
[(0, 1, 2.0), (0, 2, 4.0), (1, 0, 3.0), (2, 0, 5.0)]


## En klasse for nettverk

Vi bygger litt videre på ideen fra den første forelesningen og legger nettverket inn en klasse. Du kan legge inn funksjonene du lagde over.

Pass på at alt virker før du går videre.


In [31]:
class Nettverk:
    _piler = []
    _antallNoder = 0
    def __init__(self, antallNoder):
        self._antallNoder = antallNoder
       
    def __str__(self):
        return "Antall noder er " + str(self._antallNoder) + " med piler " + str(self._piler)
       
    def leggTilNoder(self, antallNyeNoder):
        self._antallNoder += antallNyeNoder

    def leggTilPil(self, pil):
        self._piler.append(pil)

    def leggTilPiler(self, listeNyePiler):
        self._piler += listeNyePiler
       
    def tilMatrise(self):
        n = self._antallNoder
        matrix = np.zeros((n, n))
        
        for row, col, value in self._piler:
            matrix[row][col] = value
        
        for i in range(n):
            matrix[i][i] = -np.sum(matrix[i])
        
        return matrix
    
    def fraMatrise(self, matrix):
        network = []
        m, n = np.shape(matrix)
    
        for row in range(m):
            for col in range(n):
                if row != col and matrix[row][col] != 0:
                    network.append((row, col, matrix[row][col]))
                    
        return network
    
N = Nettverk(3)  # et nettverk med 3 noder
N.leggTilPiler([(0, 1, 2.0), (1, 0, 3.0), (0, 2, 4.0), (2,0,5.0)])
print(N)
print("Matrisen til N er", N.tilMatrise())
M = np.array([[0.0, 2.0, 4.0],[3.0, 0.0, 0.0], [5.0, 0.0, 0.0]])
N.fraMatrise(M)
print(N)


Antall noder er 3 med piler [(0, 1, 2.0), (1, 0, 3.0), (0, 2, 4.0), (2, 0, 5.0)]
Matrisen til N er [[-6.  2.  4.]
 [ 3. -3.  0.]
 [ 5.  0. -5.]]
Antall noder er 3 med piler [(0, 1, 2.0), (1, 0, 3.0), (0, 2, 4.0), (2, 0, 5.0)]


## Oppgave 2

Gjør implementasjonen av "leggTilPil" og "leggTilPiler" litt mer brukervennlig. 

a) Skriv ut en feilmelding hvis noen prøver å legge til en løkke (f.eks. pil (1,1,1.0))

b) Skriv ut en feilmelding hvis noen prøver å legge til en pil som referer til en node som ikke finnes. F.eks. hvis vi har 4 noder, så har disse navn 0,1,2,3, så det skal komme feilmelding hvis noen prøver for eksempel å legge til pilen (1,4,0.1), da vi ikke har noen node med navn 4. 

Det skal være informasjon om hva som er feil i feilmeldingene!

Du kan teste hva du har gjort med koden under.

Bonus: Du kan også prøve å gjøre "fraMatrise" mer brukervennlig ved å skrive feilmelding hvis matrisen har feil format.

In [29]:
class Nettverk:
    _piler = []
    _antallNoder = 0
    def __init__(self, antallNoder):
        self._antallNoder = antallNoder
       
    def __str__(self):
        return "Antall noder er " + str(self._antallNoder) + " med piler " + str(self._piler)
       
    def leggTilNoder(self, antallNyeNoder):
        self._antallNoder += antallNyeNoder

    def leggTilPil(self, pil):        
        if pil[0] == pil[1]:
            raise ValueError("an arrow can not have the same start and end node")
        if not 0 <= pil[0] <= self._antallNoder or not 0 <= pil[1] <= self._antallNoder:
            raise ValueError("arrow can not point to a node that does not exist")
        
        self._piler.append(pil)

    def leggTilPiler(self, listeNyePiler):
        for pil in listeNyePiler:
            if pil[0] == pil[1]:
                raise ValueError("an arrow can not have the same start and end node")
            if not 0 <= pil[0] <= self._antallNoder or not 0 <= pil[1] <= self._antallNoder:
                raise ValueError("arrow can not point to a node that does not exist")
        
        self._piler += listeNyePiler
        
    def tilMatrise(self):
        n = self._antallNoder
        matrix = np.zeros((n, n))
        
        for row, col, value in self._piler:
            matrix[row][col] = value
        
        for i in range(n):
            matrix[i][i] = -np.sum(matrix[i])
        
        return matrix
    
    def fraMatrise(self, matrix):
        network = []
        m, n = np.shape(matrix)
    
        for row in range(m):
            for col in range(n):
                if row != col and matrix[row][col] != 0:
                    network.append((row, col, matrix[row][col]))
                    
        return network

In [30]:
#
# Når du tester klassen din så skal det skrives ut feilmeldinger her.
#
N = Nettverk(4)
N.leggTilPil((0,0,0.2))
N.leggTilPil((1,4,0.1))
N.leggTilPil((1,-1,0.1))
N.leggTilPiler([(1,4,0.1), (1,-1,0.1)])

(0, 0, 0.2)


ValueError: an arrow can not have the same start and end node

## Lineære dynamiske systemer og Eulers metode

Vi ser på det dynamiske systemet gitt ved et system av ordinære lineære differensiallikninger (med konstante koeffisienter).

$$
y' = y \cdot A
$$

Her er $A$ en konstant matrise, og $y'$ og $y$ er vektorer hvor $(y')_i = \frac{dy_i}{dt}$.

(Hvis vi hadde jobbet med kolonnevektorer så ville systemet ha vært $y' = A\cdot y$.)

### Initialverdier og randbetingelser

Vi har gjerne en verdi $y(t_0)$ som bestemmer tilstanden når systemet starter. Dette kalles en "initialverdi".

I tillegg så kan det for noen $i$ være slik at $y(t)_i=y_i$ for alle $t$. Dvs. verdien til $y(t)_i$ holdes konstant uavhengig av $t$. Dette er et eksempel på det som kalles en "randbetingelse".

Både initialverdier og randbetingelser er nyttige når vi analyserer nettverk. Vi kommer til å holde oss til initialverdier for denne gang. 

Vi skal løse systemet $y' = y\cdot A$ numerisk med Eulers metode.



In [21]:
#
# Implementasjon av Eulers metode
#

A = np.array([[-1.1, 1.1],[1.2,-1.2]]) # Systemet er y' = y @ A
y = np.array([1.0,0.0])                # initialverdibetingelse y(start)

start = 0.0   # starttid
stopp = 10.0   # slutttid
dt = 0.001    # skrittlengde
t = start
while t < stopp + dt:
    y = y + dt * (y @ A)
    t += dt
print(y)

[0.52173913 0.47826087]


### Oppgave 3

Legg til metoden "euler" med parametre starttid, stopptid, initialverdier, skrittlengde i klassen Nettverk. 

Metoden "euler" skal kalle metoden "fraMatrise" for å lage matrisen A i eksemplet over. 

Når du er ferdig så kan du teste ved å se om koden under gi akkurat samme resultat som over.

In [23]:
class Nettverk:
    _piler = []
    _antallNoder = 0
    def __init__(self, antallNoder):
        self._antallNoder = antallNoder
       
    def __str__(self):
        return "Antall noder er " + str(self._antallNoder) + " med piler " + str(self._piler)
       
    def leggTilNoder(self, antallNyeNoder):
        self._antallNoder += antallNyeNoder

    def leggTilPil(self, pil):
        print(pil)
        
        if pil[0] == pil[1]:
            raise ValueError("an arrow can not have the same start and end node")
        if not 0 <= pil[0] <= self._antallNoder or not 0 <= pil[1] <= self._antallNoder:
            raise ValueError("arrow can not point to a node that does not exist")
        
        self._piler.append(pil)

    def leggTilPiler(self, listeNyePiler):
        for pil in listeNyePiler:
            if pil[0] == pil[1]:
                raise ValueError("an arrow can not have the same start and end node")
            if not 0 <= pil[0] <= self._antallNoder or not 0 <= pil[1] <= self._antallNoder:
                raise ValueError("arrow can not point to a node that does not exist")
        
        self._piler += listeNyePiler
        
    def tilMatrise(self):
        max_index = max(max(i, j) for i, j, w in self._piler)
    
        matrix_size = max_index + 1
        
        matrix = np.zeros((matrix_size, matrix_size))
        
        for i, j, w in self._piler:
            matrix[i][j] = w
        
        for i in range(matrix_size):
            matrix[i][i] = -np.sum(matrix[i])
        
        return matrix
    
    def fraMatrise(self, matrix):
        network = []
    
        num_rows, num_cols = matrix.shape
        
        for i in range(num_rows):
            for j in range(num_cols):
                if i != j and matrix[i][j] != 0:
                    network.append((i,j,matrix[i][j]))
                    
        return network
    
    def euler(self, start, stopp, y, h):
        A = self.tilMatrise()
        t = start
        
        while t < stopp + h:
            y += y + h * (y @ A)
            t += h
        return y
    

In [24]:
#
# Du kan teste ved å kjøre dette
#

A = np.array([[-1.1, 1.1],[1.2,-1.2]]) 
y0 = np.array([1.0,0.0]) 
N = Nettverk(2)
N.fraMatrise(A)

start = 0.0  
stopp = 10.0  
dt = 0.001   
resultat = N.euler(start, stopp, y0, dt)
print(resultat)

ValueError: max() arg is an empty sequence

## En modell for websurfing

Vi skal lage en enkel modell for webtrafikk. Nodene i nettverket er websider. 

Vi tenker oss at noen (eller noe) som surfer på nettet gjør en av følgende to ting

1. De leser litt på en side, før de følger en lenke til en annen side, eller

2. De leser litt på en side, før de hopper til en annen vilkårlig annen side i nettet.

Det er ingen løkker i dette nettverket.

1. Det er en pil i->j hvis det er en lenke fra side i til side j. Pilen $i->j$ har vekt $0.8$.

2. Det er en pil fra hver node til alle andre noder i nettverket. Alle disse pilene har en vekt $0.2$.

Slik at du slipper å skrive så mye, så gir vi et tips under om hvordan vi kan lage matrisen for 2. i feltet under. Du kan ignorere dette om du vil.

Vi ser på et enkelt eksempel med 6 websider med navn 0,..,5. Vi har følgende lenker mellom sidene:

0->1

1->2

2->1

3->0

3->1

4->1

4->3

4->5

5->1

5->4


## Oppgave 

a) Lag nettverket med riktige vekter, hvor du tar både adferden 1. og 2. med i betraktning.

Vi kan da se hvordan webtraffikken utvikler seg over tid ved å bruke Eulers metode. Vi bruker
intialverdien $y(0) = (1,0,0,0,0,0)$. Dvs. alle er på side $0$ når vi starter. $y(t)$ vil gi prosentvis fordeling
av surferne ved tid $t$.

b) Bruk Eulers metode til å se fordeling av surferne ved tid t = 1.0 og t = 2.0. Pass på at skrittlengden er liten nok til at du får konvergens.

c) Eksperimenter med større verdier for $t$ og prøv å finn ut hva som skjer når $t\rightarrow \infty$.

d) Hvilken av disse sidene er mest populær?


In [60]:
#
# Tips om hvordan du kan lage matrise for del 2. Vi tar differansen av en matrise med bare 1'ere med identitetsmatrisen

H = np.ones(shape=(6,6)) - 6.0*np.eye(6)
print(H)


[[-5.  1.  1.  1.  1.  1.]
 [ 1. -5.  1.  1.  1.  1.]
 [ 1.  1. -5.  1.  1.  1.]
 [ 1.  1.  1. -5.  1.  1.]
 [ 1.  1.  1.  1. -5.  1.]
 [ 1.  1.  1.  1.  1. -5.]]


In [61]:
#
# Lever svaret ditt her
#